[versions]
agp = "9.3.2"
appcompat = "1.8.0"
material = "1.14.0"
activity = "1.13.0"
constraintlayout = "2.2.2"
mxparser = "6.1.1"
mediarouter = "1.8.1"
gson = "2.14.0"
json = "20260814"
viewpager2 = "1.1.0"
securityCrypto = "1.1.0"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
mariuszgromada-mathparser-org-mxparser = { module = "org.mariuszgromada.math:MathParser.org-mXparser", version.ref = "mxparser" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
mediarouter = { group = "androidx.mediarouter", name = "mediarouter", version.ref = "mediarouter" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
json = { group = "org.json", name = "json", version.ref = "json" }
viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
security-crypto = { group = "androidx.security", name = "security-crypto", version.ref = "securityCrypto" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

